# Configuration file for your GitHub Pages site

# Site settings
title: School Notes
description: A collection of notes for various subjects
baseurl: "/school-notes" # The subpath of your site, if you're hosting it on a subpath (optional)

# Theme settings (using a remote Jekyll theme)
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme # Make sure this plugin is enabled for remote themes

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
